/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dell
 */
public class fenetre extends javax.swing.JFrame {
    public int[] nombres;
    public int[] objectif;
    int tentatives_nb;
    boolean fin_jeu;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetre.class.getName());

    /**
     * Creates new form fenetre
     */
    public fenetre() {
         initComponents();
        visibilite(false);
        initJeu();
        perdu.setVisible(false); 
        actualiserLabels();
    }
private void visibilite(boolean valeur) {
        up0.setVisible(valeur);
        up1.setVisible(valeur);
        up2.setVisible(valeur);
        up3.setVisible(valeur);
        tentatives_1.setVisible(valeur);
        jLabel5.setVisible(valeur);
        jLabel4.setVisible(valeur);
        jLabel3.setVisible(valeur);
        jLabel2.setVisible(valeur);
        jLabel8.setVisible(valeur);
        down0.setVisible(valeur);
        down1.setVisible(valeur);
        down2.setVisible(valeur);
        down3.setVisible(valeur);
        pari.setVisible(valeur);
        tester.setVisible(valeur);
        recommencer.setVisible(valeur);

        jLabel1.setVisible(valeur);
        jLabel2.setVisible(valeur);
        jLabel5.setVisible(valeur);
        jLabel6.setVisible(valeur);
        jLabel7.setVisible(valeur);
        
        
        exact.setVisible(valeur);
        hauts.setVisible(valeur);
        bas.setVisible(valeur);
        tentatives.setVisible(valeur);
        
        parit.setVisible(valeur);
        
        jouer.setVisible(!valeur);
    }
    private void initJeu() {
        
        tentatives_nb = 0;
        System.out.println("Hello");
        fin_jeu = false;
        nombres = new int[]{0, 0, 0, 0};
        objectif = new int[]{0, 0, 0, 0};    
        for (int i = 0; i < 4; i++) {
            objectif[i] = (int)(Math.random() * 10); 
        }
        actualiserDevinette();
        actualiserLabels();      
        tentatives.setText("0 sur 5");
        perdu.setText("Perdu");
        perdu.setVisible(false);
    }
    
    private void actualiserDevinette() {
        int exact_nb = 0;
        int hauts_nb = 0;
        int bas_nb = 0;
        for (int i = 0; i < 4; i++) {
            if (nombres[i] == objectif[i]) {
                exact_nb++;
            } else if (nombres[i] > objectif[i]) {
                hauts_nb++;
            } else {
                bas_nb++;
            }
        
        }
        exact.setText(String.valueOf(exact_nb));
        bas.setText(String.valueOf(bas_nb));
        hauts.setText(String.valueOf(hauts_nb));
        
        if (exact_nb == 4) {
            perdu.setText("Gagné " + String.valueOf(Float.parseFloat(pari.getText()) * 2) + " euros!");
            perdu.setVisible(true);
            fin_jeu = true;
                    
        }
    }
    
    private void actualiserLabels() {
        jLabel5.setText(String.valueOf(nombres[0]));
        jLabel4.setText(String.valueOf(nombres[1]));
        jLabel3.setText(String.valueOf(nombres[2]));
        jLabel2.setText(String.valueOf(nombres[3]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        up0 = new javax.swing.JButton();
        up1 = new javax.swing.JButton();
        up2 = new javax.swing.JButton();
        tester = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        down3 = new javax.swing.JButton();
        down2 = new javax.swing.JButton();
        down1 = new javax.swing.JButton();
        down0 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tentatives = new javax.swing.JLabel();
        recommencer = new javax.swing.JButton();
        tentatives_1 = new javax.swing.JLabel();
        exact = new javax.swing.JLabel();
        hauts = new javax.swing.JLabel();
        bas = new javax.swing.JLabel();
        perdu = new javax.swing.JLabel();
        parit = new javax.swing.JLabel();
        jouer = new javax.swing.JButton();
        up3 = new javax.swing.JButton();
        pari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadenas juego");

        up0.setText("/\\");
            up0.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up0ActionPerformed(evt);
                }
            });

            up1.setText("/\\");
                up1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up1ActionPerformed(evt);
                    }
                });

                up2.setText("/\\");
                    up2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up2ActionPerformed(evt);
                        }
                    });

                    tester.setText("Tester");
                    tester.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            testerActionPerformed(evt);
                        }
                    });

                    jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
                    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel2.setText("jLabel2");
                    jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

                    jLabel3.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
                    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel3.setText("jLabel3");
                    jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

                    jLabel4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
                    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel4.setText("jLabel4");
                    jLabel4.setToolTipText("");
                    jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

                    jLabel5.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
                    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel5.setText("jLabel5");
                    jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

                    down3.setText("\\/");
                    down3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down3ActionPerformed(evt);
                        }
                    });

                    down2.setText("\\/");
                    down2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down2ActionPerformed(evt);
                        }
                    });

                    down1.setText("\\/");
                    down1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down1ActionPerformed(evt);
                        }
                    });

                    down0.setText("\\/");
                    down0.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down0ActionPerformed(evt);
                        }
                    });

                    jLabel6.setText("nombre de chiffres exacts");

                    jLabel7.setText("nombre de chiffres trop haut");

                    jLabel8.setText("nombre de chiffres trop bas");

                    tentatives.setText("tentatives");

                    recommencer.setText("recommencer");
                    recommencer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            recommencerActionPerformed(evt);
                        }
                    });

                    tentatives_1.setText("nombre de tentative");

                    exact.setText("jLabel11");

                    hauts.setText("jLabel12");

                    bas.setText("jLabel13");

                    perdu.setText("perdu");

                    parit.setText("Pari  :");

                    jouer.setText("jouer");
                    jouer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jouerActionPerformed(evt);
                        }
                    });

                    up3.setText("/\\");
                        up3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up3ActionPerformed(evt);
                            }
                        });

                        pari.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                pariActionPerformed(evt);
                            }
                        });

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(down0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(6, 6, 6)
                                            .addComponent(down1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(down2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(down3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(perdu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(360, 360, 360)
                                                .addComponent(tester))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(exact)
                                                    .addComponent(hauts)
                                                    .addComponent(bas))
                                                .addGap(55, 55, 55))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(up0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(up1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(15, 15, 15)
                                                .addComponent(up2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(up3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tentatives_1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(recommencer))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(parit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jouer)
                                        .addGap(107, 107, 107)
                                        .addComponent(jLabel1)))
                                .addGap(0, 0, Short.MAX_VALUE))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jouer)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel1)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(up0)
                                    .addComponent(up1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(up2)
                                            .addComponent(up3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(parit)
                                            .addComponent(pari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(down0)
                                            .addComponent(down1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(down2)
                                                .addComponent(down3)))
                                        .addGap(10, 10, 10)
                                        .addComponent(tester)
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tentatives_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(4, 4, 4)
                                                .addComponent(recommencer))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel7)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel8))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(exact)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(hauts)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(bas))))))
                                    .addComponent(perdu)))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ActionPerformed
nombres[1] = (nombres[1] + 1) % 10;
        actualiserLabels();        // TODO add your handling code here:
    }//GEN-LAST:event_up1ActionPerformed

    private void down1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down1ActionPerformed
nombres[1] = (nombres[1] + 9) % 10;
        actualiserLabels();        // TODO add your handling code here:
    }//GEN-LAST:event_down1ActionPerformed

    private void up0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up0ActionPerformed
  nombres[0] = (nombres[0] + 1) % 10;
        actualiserLabels();        // TODO add your handling code here:
    }//GEN-LAST:event_up0ActionPerformed

    private void recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommencerActionPerformed
  initJeu();        // TODO add your handling code here:
    }//GEN-LAST:event_recommencerActionPerformed

    private void up2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up2ActionPerformed
nombres[2] = (nombres[2] + 1) % 10;
        actualiserLabels();        // TODO add your handling code here:
    }//GEN-LAST:event_up2ActionPerformed

    private void down0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down0ActionPerformed
nombres[0] = (nombres[0] + 9) % 10;
        actualiserLabels();        // TODO add your handling code here:
    }//GEN-LAST:event_down0ActionPerformed

    private void down2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down2ActionPerformed
nombres[2] = (nombres[2] + 9) % 10;
        actualiserLabels();        // TODO add your handling code here:
    }//GEN-LAST:event_down2ActionPerformed

    private void down3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down3ActionPerformed
 nombres[3] = (nombres[3] + 9) % 10;
        actualiserLabels();        // TODO add your handling code here:
    }//GEN-LAST:event_down3ActionPerformed

    private void testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testerActionPerformed
                                      
        actualiserDevinette();
        if (!fin_jeu) {
            tentatives_nb++;
        }
        tentatives.setText(String.valueOf(tentatives_nb) + " sur 5");
        if (tentatives_nb == 5) {
            if (!fin_jeu) {
                System.out.print("[");
                for (int i = 0; i < 4; i++) {
                    System.out.print(objectif[i]);
                    System.out.print(", ");
                }
                System.out.print("]");
            }
            perdu.setVisible(true);
            fin_jeu = true;
          
        }
                             // TODO add your handling code here:
    }//GEN-LAST:event_testerActionPerformed

    private void jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouerActionPerformed
 visibilite(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jouerActionPerformed

    private void up3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up3ActionPerformed
if (!fin_jeu) { // Ouvrir l'accolade
    nombres[3] = (nombres[3] + 1) % 10;
    actualiserLabels();
} 

    }//GEN-LAST:event_up3ActionPerformed

    private void pariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pariActionPerformed

      
    
   public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetre().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bas;
    private javax.swing.JButton down0;
    private javax.swing.JButton down1;
    private javax.swing.JButton down2;
    private javax.swing.JButton down3;
    private javax.swing.JLabel exact;
    private javax.swing.JLabel hauts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jouer;
    private javax.swing.JTextField pari;
    private javax.swing.JLabel parit;
    private javax.swing.JLabel perdu;
    private javax.swing.JButton recommencer;
    private javax.swing.JLabel tentatives;
    private javax.swing.JLabel tentatives_1;
    private javax.swing.JButton tester;
    private javax.swing.JButton up0;
    private javax.swing.JButton up1;
    private javax.swing.JButton up2;
    private javax.swing.JButton up3;
    // End of variables declaration//GEN-END:variables
}
