/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package miniprojet_cadenaas_serghini_marwane;



public class cadenajuego extends javax.swing.JFrame {
    public int[] nombres;
    public int[] objectif;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadenajuego.class.getName());

    /**
     * Creates new form Devoir
     */
    public cadenajuego() {
        initJeu();
        initComponents();
        actualiserLabels();
    }
    
    private void initJeu() {
        nombres = new int[]{1, 2, 3, 4};
        objectif = new int[]{0, 0, 0, 0};
        for (int i = 0; i < 4; i++) {
            objectif[i] = (int)(Math.random() * 10); 
        }
    }
    
    private void actualiserLabels() {
        label0.setText(String.valueOf(nombres[0]));
        label1.setText(String.valueOf(nombres[1]));
        label2.setText(String.valueOf(nombres[2]));
        label3.setText(String.valueOf(nombres[3]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        up0 = new javax.swing.JButton();
        up1 = new javax.swing.JButton();
        up2 = new javax.swing.JButton();
        up3 = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        label0 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        down0 = new javax.swing.JButton();
        down1 = new javax.swing.JButton();
        down2 = new javax.swing.JButton();
        down3 = new javax.swing.JButton();
        tester = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exact = new javax.swing.JLabel();
        hauts = new javax.swing.JLabel();
        bas = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        recommencer = new javax.swing.JButton();
        tentatives = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        up0.setText("⇑");
        up0.addActionListener(this::up0ActionPerformed);

        up1.setText("⇑");
        up1.addActionListener(this::up1ActionPerformed);

        up2.setText("⇑");
        up2.addActionListener(this::up2ActionPerformed);

        up3.setText("⇑");
        up3.addActionListener(this::up3ActionPerformed);

        label3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("0");
        label3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label0.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label0.setText("0");
        label0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("0");
        label1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("0");
        label2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        down0.setText("⇓");
        down0.addActionListener(this::down0ActionPerformed);

        down1.setText("⇓");
        down1.addActionListener(this::down1ActionPerformed);

        down2.setText("⇓");
        down2.addActionListener(this::down2ActionPerformed);

        down3.setText("⇓");
        down3.addActionListener(this::down3ActionPerformed);

        tester.setText("Tester");
        tester.addActionListener(this::testerActionPerformed);

        jLabel5.setText("Nombre de chiffres exacts :");

        jLabel6.setText("Nombre de chiffres trop hauts : ");

        jLabel7.setText("Nombre de chiffres trop bas : ");

        exact.setText("0");

        hauts.setText("0");

        bas.setText("0");

        jLabel11.setText("Tentatives");

        recommencer.setText("Recommencer");
        recommencer.addActionListener(this::recommencerActionPerformed);

        tentatives.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tentatives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tentatives.setText("0 sur 5");
        tentatives.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(up0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label0, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addComponent(down0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(down1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(up1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(225, 225, 225)
                            .addComponent(jLabel11)
                            .addGap(95, 95, 95))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(down2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(down3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(up2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(up3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tester)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bas)
                    .addComponent(hauts)
                    .addComponent(exact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recommencer, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(up0)
                    .addComponent(up1)
                    .addComponent(up2)
                    .addComponent(up3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tester)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(down0)
                    .addComponent(down1)
                    .addComponent(down2)
                    .addComponent(down3))
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(exact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hauts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bas)))
                    .addComponent(tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(recommencer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        label3.getAccessibleContext().setAccessibleName("jLabel");

        pack();
    }// </editor-fold>                        

    private void up0ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        nombres[0] = (nombres[0] + 1) % 10;
        actualiserLabels();
    }                                   

    private void recommencerActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        nombres[1] = (nombres[1] + 1) % 10;
        actualiserLabels();
    }                                   

    private void up2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        nombres[2] = (nombres[2] + 1) % 10;
        actualiserLabels();
    }                                   

    private void up3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        nombres[3] = (nombres[3] + 1) % 10;
        actualiserLabels();
    }                                   

    private void down0ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        nombres[0] = (nombres[0] + 9) % 10;
        actualiserLabels();
    }                                     

    private void down1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        nombres[1] = (nombres[1] + 9) % 10;
        actualiserLabels();
    }                                     

    private void down2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        nombres[2] = (nombres[2] + 9) % 10;
        actualiserLabels();
    }                                     

    private void down3ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        nombres[3] = (nombres[3] + 9) % 10;
        actualiserLabels();
    }                                     

    private void testerActionPerformed(java.awt.event.ActionEvent evt) {                                       
        int exact_nb = 0;
        int hauts_nb = 0;
        int bas_nb = 0;
        for (int i = 0; i < 4; i++) {
            if (nombres[i] == objectif[i]) {
                exact_nb++;
            } else if (nombres[i] > objectif[i]) {
                hauts_nb++;
            } else {
                bas_nb++;
            }
        }
        exact.setText(String.valueOf(exact_nb));
        bas.setText(String.valueOf(bas_nb));
        hauts.setText(String.valueOf(hauts_nb));

    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadenajuego().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bas;
    private javax.swing.JButton down0;
    private javax.swing.JButton down1;
    private javax.swing.JButton down2;
    private javax.swing.JButton down3;
    private javax.swing.JLabel exact;
    private javax.swing.JLabel hauts;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JButton recommencer;
    private javax.swing.JLabel tentatives;
    private javax.swing.JButton tester;
    private javax.swing.JButton up0;
    private javax.swing.JButton up1;
    private javax.swing.JButton up2;
    private javax.swing.JButton up3;
    // End of variables declaration                   
}
