/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dell
 */
public class fenetre extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetre.class.getName());

    /**
     * Creates new form fenetre
     */
    public fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        up0 = new javax.swing.JButton();
        up1 = new javax.swing.JButton();
        up2 = new javax.swing.JButton();
        up3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        down3 = new javax.swing.JButton();
        down2 = new javax.swing.JButton();
        down1 = new javax.swing.JButton();
        down0 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        exact = new javax.swing.JLabel();
        hauts = new javax.swing.JLabel();
        bas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cadenas juego");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 17, -1, -1));

        up0.setText("/\\");
            getContentPane().add(up0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, 49, -1));

            up1.setText("/\\");
                up1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up1ActionPerformed(evt);
                    }
                });
                getContentPane().add(up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 39, 48, -1));

                up2.setText("/\\");
                    getContentPane().add(up2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 39, 48, -1));

                    up3.setText("/\\");
                        up3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 39, 48, -1));

                        jButton5.setText("Tester");
                        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

                        jLabel2.setText("jLabel2");
                        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 80, 37, -1));

                        jLabel3.setText("jLabel3");
                        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 37, -1));

                        jLabel4.setText("jLabel4");
                        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 80, 37, -1));

                        jLabel5.setText("jLabel5");
                        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 80, 37, -1));

                        down3.setText("\\/");
                        getContentPane().add(down3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 127, 45, -1));

                        down2.setText("\\/");
                        getContentPane().add(down2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 127, 51, -1));

                        down1.setText("\\/");
                        down1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 127, 47, -1));

                        down0.setText("\\/");
                        getContentPane().add(down0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 127, 53, -1));

                        jLabel6.setText("nombre de chiffres exacts");
                        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, -1));

                        jLabel7.setText("nombre de chiffres trop haut");
                        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, -1));

                        jLabel8.setText("nombre de chiffres trop bas");
                        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, -1));

                        jLabel9.setText("jLabel9");
                        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 37, -1));

                        jButton10.setText("recommencer");
                        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 250, -1, -1));

                        jLabel10.setText("jLabel10");
                        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 43, -1));

                        exact.setText("jLabel11");
                        getContentPane().add(exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

                        hauts.setText("jLabel12");
                        getContentPane().add(hauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

                        bas.setText("jLabel13");
                        getContentPane().add(bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up1ActionPerformed

    private void up3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up3ActionPerformed

    private void down1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetre().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bas;
    private javax.swing.JButton down0;
    private javax.swing.JButton down1;
    private javax.swing.JButton down2;
    private javax.swing.JButton down3;
    private javax.swing.JLabel exact;
    private javax.swing.JLabel hauts;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton up0;
    private javax.swing.JButton up1;
    private javax.swing.JButton up2;
    private javax.swing.JButton up3;
    // End of variables declaration//GEN-END:variables
}
